version: "3.8"
services:
    www:
        build: .
        ports: 
            - "10000:80"
        volumes:
            - .:/var/www/html
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: prueba
            MYSQL_ROOT_PASSWORD: prueba
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: prueba
volumes:
    persistent: